# Displayed title TODO: customize
site_name: School
# General description
site_description: Recueil de mes prises de notes liées aux cours dispensés au CFA et à l'université, ainsi que quelques exercices et d'autres médias.
# Author of the site
site_author: Tim FROLOV
# Copyright notice in the footer
#copyright: Copyright &copy; 2015 - 2023 Tim FROLOV
# URL of the site
site_url: https://flaghunter01.github.io/school
# URL of the GitHub repo TODO: customize
repo_url: https://github.com/flaghunter01/school
# Name of the repo TODO: customize
repo_name: FlagHunter01/school
# URL of docs folder FIXME: comment if help not wanted!
edit_uri: edit/main/docs/



nav:
    - Accueil: index.md
    - Université: 
      - uni/index.md
      - Management de la cyber: uni/management/index.md
      - Audit cyber: uni/audit/index.md
      - Sécurité des infrastructures: uni/infra/index.md
      - Security by design: uni/design/index.md
      - Détection et réaction: uni/detection/index.md
      - Nouvelles technologies de la cyber: uni/tech/index.md
    - CFA:
      - cfa/index.md
      - Cyberops: cfa/cyberops/index.md
      - Anglais: cfa/anglais/index.md
      - Sécurité: cfa/secu/index.md
      - Cannaux auxiliaires: cfa/cannaux/index.md
      - Crypro: cfa/crypto/index.md
      - Forensic CNPP: cfa/forensic/index.md
    - M1: 
      - m1/m1.md
      - CFA:
        - Anglais: m1/cfa/anglais.md
        - Language C: m1/cfa/c/c.md
        - BDD: m1/cfa/bdd.md
        - Sécurité Linux: m1/cfa/secu.md
#      - CCNA 1: cfa/ccna1.md
#    - CCNA 2:
#       - cfa/ccna2/index.md
#       - 1 - Configuration de base des périphériques: cfa/ccna2/1.md
#       - 2 - Concepts de Commutation: cfa/ccna2/2.md
#       - 3 - VLANs: cfa/ccna2/3.md
#       - 4 - Routage inter-VLAN: cfa/ccna2/4.md
#       - 5 - Concepts du STP: cfa/ccna2/5.md
#       - 6 - EtherChannel: cfa/ccna2/6.md
#       - 7 - DHCPv4: cfa/ccna2/7.md
#       - 8 - SLAAC et DHCPv6: cfa/ccna2/8.md
#       - 9 - Concepts du FHRP: cfa/ccna2/9.md
#       - 10 - Concepts de sécurité de LAN: cfa/ccna2/10.md
#       - 11 - Configuration de la sécurité du commutateur: cfa/ccna2/11.md
#       - 12 - Concepts WLAN: cfa/ccna2/12.md
#       - 13 - La configuration WLAN: cfa/ccna2/13.md
#       - 14 - Concepts de routage: cfa/ccna2/14.md
#       - 15 - Routage statique IP: cfa/ccna2/15.md
#       - 16 - Dépannage des routes statiques et par défaut: cfa/ccna2/16.md
#    - CCNA 3:
#      - cfa/ccna3/index.md
#      - 1 - Concepts de l'OSPF a zone unique: cfa/ccna3/1.md
#      - 2 - Configuration OSPFv2 à zone unique: cfa/ccna3/2.md
#      - 3 - Concepts de sécurité des réseaux: cfa/ccna3/3.md
#      - 4 - Concepts de liste de contrôle d'accès (ACL): cfa/ccna3/4.md
#      - 5 - Configuration de liste de contrôle d'accès pour IPv4: cfa/ccna3/5.md
#      - 6 - NAT pour IPv4: cfa/ccna3/6.md
#      - 7 - Concepts WAN: cfa/ccna3/7.md
#      - 8 - Concepts de VPN et IPSec: cfa/ccna3/8.md
#      - 9 - Concepts QoS: cfa/ccna3/9.md
#    - CCNA 3 - REPONSES: cfa/ccna3/rep.md
#    - Université:
      - Université:
        - Réseau: m1/uni/reseau.md
        - Maths: m1/uni/maths.md
        - Sécurité: m1/uni/securite.md
    - Misc: m1/misc.md
#    - NOTRE PROJET: projet.md


theme:
  name: material

  # 1 per project (HTML5 limitation)
  language: fr

  logo: assets/logo.png
  #icon:
  #  logo: fontawesome/solid/rocket
  favicon: assets/logo.png

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


  font:
    text: Roboto
    code: Roboto Mono


  features:
    # Copy to clipboard button in code blocks
    - content.code.copy
    # Next and previous buttons in footer
    - navigation.footer
    # Monopage architecture (TODO: does it work?)
    - navigation.instant
    # Update URL with current anchor
    - navigation.tracking
    # Show tabs in the top menu
    - navigation.tabs
    # Show tabs in the left menu
    - navigation.sections
    # Auto-expand left menu
    - navigation.expand
    # Breadcrumbs displayed on top of the page
    - navigation.path
    # First page of section serves as a preview (https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages)
    - navigation.indexes
    # Autoscroll menus so the current page is allways visible
    - toc.follow
    # Back to top button
    - navigation.top
    # Search auto completion
    - search.suggest
    # Hightlight search results
    - search.highlight
    # Link content tabs togeather across the page
    - content.tabs.link
    # Better tooltips
    - content.tooltips
    # Link to source code
    - content.action.edit


plugins:
  # Self-host all ressources aka fonts, icons etc (RGPD)
  #- privacy
  # Client side search
  - search
  # Social cards - previews on social networks. Can't figure it out for Windows yet.
  - social
  # Blog. Required arborescence: https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#built-in-blog-plugin
  #- blog
  # Table of contents keeps the formating (icons, underline etc)
  #- typeset


  # Revision date info for GitHub repos TODO: uncomment if repo
  - git-revision-date-localized:
      enable_creation_date: true
      #fallback_to_build_date: true
  - git-committers:
      repository: FlagHunter01/school
      branch: main
  #- git-authors
  # Optimize for offline use
  - offline


extra:
  # Page status that can be displayed
  status:
    new: Nouveau
    deprecated: Contrôle passé
  # Social links in the footer
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/flaghunter01/
  # Main logo link URL. site_url by default
  #homepage: site_url


  # Multiple languages support
  #alternate:
  #   - name: English
  #     link: /en/
  #     lang: en
  #   - name: Français
  #     link: /fr/
  #     lang: fr

markdown_extensions:
  # Support for admonitions
  - admonition
  # Annotations, grids, buttons, tooltips, colored icons, image alignment and lazy images
  - attr_list
  # Add footnotes
  - footnotes
  # Allows the useagse of HTML
  - md_in_html
  # Generates tables of content.
  - toc:
      # Visible anchor
      permalink: ⚓︎
  # Draw tables
  - tables
  # Underline and superscript
  - pymdownx.caret
  # Hightlight
  - pymdownx.mark
  # Subscript and deleted
  - pymdownx.tilde
  # make admonitions colabseable
  - pymdownx.details
  # Emoji support
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # Highlight code blocks
  - pymdownx.highlight:
      anchor_linenums: true
  # Nesting of just about everything
  - pymdownx.superfences
  # Draw keys
  - pymdownx.keys
  # Separate content into different tabs
  - pymdownx.tabbed:
      alternate_style: true
  # Taxk lists
  - pymdownx.tasklist:
      custom_checkbox: true

#extra_css:
#  - stylesheets/extra.css
